import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Graph({data}) {
  const people = data.results;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          {
            people.map(person => {
              return (
                <div key={person.id} className={`${styles.card}`}>
                  <Image
                    src={`https://image.tmdb.org/t/p/original${person.profile_path}`}
                    alt={`Profile photo from ${person.name}`}
                    width={200}
                    height={150}
                    // layout={'fill'}
                  />
                  <p>{person.name}</p>
              </div>
              )
            })
          }
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps() {
const APIKEY = process.env.API_KEY
const URL = `https://api.themoviedb.org/3/person/popular?api_key=${APIKEY}`

  const res = await fetch(URL)
  const data = await res.json()

  if (!data) {
    return {
      notFound: true,
    }
  }
  return {
    props: {
      data
    }
  }
}
