import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import svgstyle from '../styles/SVG.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <div className={`${styles.card} ${svgstyle.svgExample}`}>
            <h2>Create your own SVG</h2>
            <svg width='300' height='250' className={svgstyle.example}>
              <g>
                <g className={svgstyle.eyes}>
                  <g className={svgstyle.eye}>
                    <rect x="10" y="60" width="33" height="40"></rect>
                    <rect x="43" y="60" width="33" height="40"></rect>
                    <rect x="76" y="60" width="33" height="40"></rect>
                  </g>
                  <g className={svgstyle.eye}>
                    <rect x="130" y="60" width="33" height="40"></rect>
                    <rect x="163" y="60" width="33" height="40"></rect>
                    <rect x="196" y="60" width="33" height="40"></rect>
                  </g>
                </g>
              </g>
            </svg>
            <p className={svgstyle.title}>Sad Man</p>
          </div>
          <div className={styles.card}>
            <h2></h2>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}